import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const now = new Date();
const buildTime = now.getTime();
const buildId = 'b_' + buildTime;
const releaseDate = now.toISOString().split('T')[0];

// Base version
let currentVersion = '2.6.1';
const versionJsPath = path.join(__dirname, 'src/version.js');
if (fs.existsSync(versionJsPath)) {
  try {
    const content = fs.readFileSync(versionJsPath, 'utf8');
    const match = content.match(/APP_VERSION\s*=\s*['"]([^'"]+)['"]/);
    if (match && match[1]) {
      currentVersion = match[1];
    }
  } catch (_) {}
}

// Generate src/version.js
const versionJsContent = `// Auto-generated by generate-version.js on every build
export const APP_VERSION = '${currentVersion}';
export const APP_BUILD_TIME = ${buildTime};
export const APP_BUILD_ID = '${buildId}';
export const APP_RELEASE_DATE = '${releaseDate}';
`;
fs.writeFileSync(versionJsPath, versionJsContent, 'utf8');

// Generate public/version.json
const versionJsonData = {
  version: currentVersion,
  buildTime: buildTime,
  buildId: buildId,
  releaseDate: releaseDate,
  mandatory: true,
  title: `Eco Green Support v${currentVersion}`,
  summary: 'New official release with continuous deploy sync and optimizations.',
  features: [
    '📑 Voucher & Tour Ledger: Official Green Energy branding, ticket segregation, and formal approval stamp.',
    '⚡ Continuous Deploy Sync: Automatic detection of newly deployed features across all active devices.',
    '📲 Mobile Notifications & Map Pins: Smooth swipe dismiss and smart conditional location display.'
  ]
};

const publicVersionJsonPath = path.join(__dirname, 'public/version.json');
fs.writeFileSync(publicVersionJsonPath, JSON.stringify(versionJsonData, null, 2), 'utf8');

// Also write directly to dist if dist exists
const distPath = path.join(__dirname, 'dist');
if (fs.existsSync(distPath)) {
  fs.writeFileSync(path.join(distPath, 'version.json'), JSON.stringify(versionJsonData, null, 2), 'utf8');
}

console.log(`[Version Engine] Created build ${buildId} (timestamp: ${buildTime}) for v${currentVersion}`);
