// Auto-generated by generate-version.js on every build
export const APP_VERSION = '2.6.2';
export const APP_BUILD_TIME = 1791194946812;
export const APP_BUILD_ID = 'b_1791194946812';
export const APP_RELEASE_DATE = '2026-10-05';
