// Auto-generated by generate-version.js on every build
export const APP_VERSION = '2.6.3';
export const APP_BUILD_TIME = 1791618168688;
export const APP_BUILD_ID = 'b_1791618168688';
export const APP_RELEASE_DATE = '2026-10-10';
