version: '3.8'

services:
  eco-green-cms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eco-green-complain
    ports:
      - "10000:10000"
    environment:
      - PORT=10000
      - NODE_ENV=production
      - JWT_SECRET=egs_production_super_secret_token_2026
      - WHATSAPP_PROVIDER=SIMULATED
      - EMAIL_PROVIDER=SIMULATED
    volumes:
      - cms_uploads:/app/server/uploads
    restart: unless-stopped

volumes:
  cms_uploads:
